using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Linq;
using System.Text;
using System.Text.Json;

[Generator]
public class ErrorCodeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Регистрируем поставщика данных для embedded ресурсов
        var embeddedResources = context.AdditionalTextsProvider
            .Where(file => file.Path.EndsWith("errors.json"))
            .Select((file, cancellationToken) => file.GetText(cancellationToken)?.ToString());

        // 2. Комбинируем с компиляцией
        var compilationAndResources = context.CompilationProvider.Combine(embeddedResources.Collect());

        // 3. Регистрируем этап генерации кода
        context.RegisterSourceOutput(compilationAndResources, (productionContext, source) =>
        {
            var jsonContent = source.Right.FirstOrDefault();
            if (jsonContent == null)
            {
                productionContext.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "ERR001",
                        "JSON file not found",
                        "Could not find error_codes.json file",
                        "ErrorCodeGeneration",
                        DiagnosticSeverity.Error,
                        true),
                    Location.None));
                return;
            }

            try
            {
                // 4. Парсим JSON и генерируем код
                var json = JsonDocument.Parse(jsonContent);
                var sourceBuilder = new StringBuilder();
                GenerateErrorClasses(json, sourceBuilder);

                // 5. Добавляем сгенерированный код
                productionContext.AddSource("Errors.g.cs",
                    SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
            }
            catch (JsonException ex)
            {
                productionContext.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "ERR002",
                        "Invalid JSON format",
                        $"JSON parsing failed: {ex.Message}",
                        "ErrorCodeGeneration",
                        DiagnosticSeverity.Error,
                        true),
                    Location.None));
            }
        });
    }

    private void GenerateErrorClasses(JsonDocument json, StringBuilder sourceBuilder)
    {
        sourceBuilder.AppendLine("// <auto-generated/>");
        sourceBuilder.AppendLine("namespace MoneyTracker.SharedConstants.ErrorCodes;");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine("public static class Errors");
        sourceBuilder.AppendLine("{");

        foreach (var category in json.RootElement.GetProperty("Errors").EnumerateObject())
        {
            var categoryName = category.Name;
            sourceBuilder.AppendLine($"    public static class {categoryName}");
            sourceBuilder.AppendLine("    {");

            foreach (var error in category.Value.EnumerateObject())
            {
                var errorName = error.Name;
                var errorCode = error.Value.GetProperty("Code").GetString();
                sourceBuilder.AppendLine($"        public const string {errorName} = \"{errorCode}\";");
            }

            sourceBuilder.AppendLine("    }");
        }

        sourceBuilder.AppendLine("}");
    }
}