using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Text;
using System.Text.Json;

[Generator]
public class ErrorCodeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Регистрируем диагностический вывод для проверки инициализации
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("ErrorCodeGenerator_Init.g.cs",
                SourceText.From("// Generator initialized", Encoding.UTF8)));

        var jsonFiles = context.AdditionalTextsProvider
            .Where(file => file.Path.EndsWith("errors.json"));

        context.RegisterSourceOutput(jsonFiles, (ctx, file) =>
        {
            try
            {
                var jsonContent = file.GetText()?.ToString();
                if (string.IsNullOrWhiteSpace(jsonContent))
                {
                    ReportError(ctx, "ERR001", "JSON file is empty");
                    return;
                }

                var source = GenerateErrorClasses(jsonContent);

                // Ключевое изменение: используем простое имя файла без пути
                ctx.AddSource("Errors.g.cs", SourceText.From(source, Encoding.UTF8));
            }
            catch (Exception ex)
            {
                ReportError(ctx, "ERR002", $"Generation failed: {ex.Message}");
            }
        });
    }

    private string GenerateErrorClasses(string jsonContent)
    {
        using (var json = JsonDocument.Parse(jsonContent))
        {
            var sourceBuilder = new StringBuilder();

            sourceBuilder.AppendLine("// <auto-generated/>");
            sourceBuilder.AppendLine("// Generated by ErrorCodeGenerator");
            sourceBuilder.AppendLine("namespace MoneyTracker.SharedConstants.ErrorCodes;");
            sourceBuilder.AppendLine();
            sourceBuilder.AppendLine("public static class Errors");
            sourceBuilder.AppendLine("{");

            foreach (var category in json.RootElement.GetProperty("Errors").EnumerateObject())
            {
                var categoryName = category.Name;
                sourceBuilder.AppendLine($"    public static class {categoryName}");
                sourceBuilder.AppendLine("    {");

                foreach (var error in category.Value.EnumerateObject())
                {
                    var errorName = error.Name;
                    var errorCode = error.Value.GetProperty("Code").GetString();
                    sourceBuilder.AppendLine($"        public const string {errorName} = \"{errorCode}\";");
                }

                sourceBuilder.AppendLine("    }");
            }

            sourceBuilder.AppendLine("}");
            return sourceBuilder.ToString();
        }
    }

    private void ReportError(SourceProductionContext ctx, string id, string message)
    {
        ctx.ReportDiagnostic(Diagnostic.Create(
            new DiagnosticDescriptor(
                id, "Error Generation",
                message, "Generator",
                DiagnosticSeverity.Error, true),
            Location.None));
    }
}