name: CurrencyService CI

on:
  push:
    branches:
      - Main
      - Dev
    paths:
      - 'CurrencyService/**'
      - 'SharedKernel/**'
  pull_request:
    branches:
      - Main
      - Dev
    paths:
      - 'CurrencyService/**'
      - 'SharedKernel/**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получить код из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установить .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Шаг 3: Настроить NuGet для работы с GitHub Packages
      - name: Configure NuGet
        run: |
          sed -i 's/%GITHUB_TOKEN%/${{ secrets.PACKAGES_TOKEN }}/g' CurrencyService/nuget.config

      

      # Шаг 8: Восстановление зависимостей
      - name: Restore dependencies
        run: dotnet restore CurrencyService/srs/MoneyTracker.CurrencyService.Domain/MoneyTracker.CurrencyService.Domain.csproj

      # Шаг 9: Сборка проекта
      - name: Build project
        run: dotnet build CurrencyService/srs/MoneyTracker.CurrencyService.Domain/MoneyTracker.CurrencyService.Domain.csproj --no-restore

      # Шаг 10: Запуск тестов
      - name: Run tests
        run: dotnet test CurrencyService/tests/MoneyTracker.CurrencyService.UnitTests/MoneyTracker.CurrencyService.UnitTests.csproj

  sonar_scan:
    name: SonarQubeScan1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: CurrencyService/


