name: CurrencyService CI
on:
  push:
    branches:
      - Main
      - Dev
    paths:
      - 'CurrencyService/**'
      - 'SharedKernel/**'
  pull_request:
    branches:
      - Main
      - Dev
    paths:
      - 'CurrencyService/**'
      - 'SharedKernel/**'
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Получить код из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установить .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Шаг 3: Настроить NuGet для работы с GitHub Packages
      - name: Configure NuGet
        run: |
          sed -i 's/%GITHUB_TOKEN%/${{ secrets.PACKAGES_TOKEN }}/g' CurrencyService/nuget.config

      # Шаг 4: Кэширование SonarQube Cloud packages
      - name: Cache SonarQube Cloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Шаг 5: Кэширование SonarQube Cloud scanner
      - name: Cache SonarQube Cloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: ./.sonar/scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      # Шаг 6: Установка SonarQube Cloud scanner (если не закэшировано)
      - name: Install SonarQube Cloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          mkdir -p ./.sonar/scanner
          dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner

      # Шаг 7: Восстановление зависимостей
      - name: Restore dependencies
        run: dotnet restore CurrencyService/MoneyTracker.CurrencyService.sln

      # Шаг 8: Сборка проекта
      - name: Build project
        run: dotnet build CurrencyService/MoneyTracker.CurrencyService.sln --no-restore

      # Шаг 9: Запуск тестов с покрытием
      - name: Run tests with coverage
        run: |
          dotnet test CurrencyService/MoneyTracker.CurrencyService.sln --collect:"XPlat Code Coverage" --results-directory ./TestResults

      # Шаг 10: Проверка содержимого TestResults
      - name: List TestResults directory
        run: ls -R ./TestResults

      # Шаг 11: Запуск анализа SonarQube
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./.sonar/scanner/dotnet-sonarscanner begin /k:"DanilRukin_MoneyTracker" /o:"dvrukin" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.xunit.reportsPaths="./TestResults/**/coverage.cobertura.xml"
          dotnet build CurrencyService/MoneyTracker.CurrencyService.sln
          dotnet test CurrencyService/MoneyTracker.CurrencyService.sln --collect:"XPlat Code Coverage" --results-directory ./TestResults
          ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"